led_instruction_t led_instructions[] = {
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id0 = 1,		.r = 255, .g = 0, .b = 0 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id0 = 2,		.r = 255, .g = 255, .b = 0 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id0 = 4,		.r = 0, .g = 255, .b = 0 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id0 = 8,		.r = 0, .g = 255, .b = 255 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id0 = 16,		.r = 0, .g = 0, .b = 255 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id0 = 32,		.r = 255, .g = 0, .b = 255 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id1 = 1,		.r = 255, .g = 0, .b = 0 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id1 = 2,		.r = 255, .g = 255, .b = 0 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id1 = 4,		.r = 0, .g = 255, .b = 0 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id1 = 8,		.r = 0, .g = 255, .b = 255 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id1 = 16,		.r = 0, .g = 0, .b = 255 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id1 = 32,		.r = 255, .g = 0, .b = 255 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id2 = 1,		.r = 255, .g = 0, .b = 0 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id2 = 2,		.r = 255, .g = 255, .b = 0 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id2 = 4,		.r = 0, .g = 255, .b = 0 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id2 = 8,		.r = 0, .g = 255, .b = 255 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id2 = 16,		.r = 0, .g = 0, .b = 255 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id2 = 32,		.r = 255, .g = 0, .b = 255 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id3 = 1,		.r = 255, .g = 0, .b = 0 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id3 = 2,		.r = 255, .g = 255, .b = 0 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id3 = 4,		.r = 0, .g = 255, .b = 0 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id3 = 8,		.r = 0, .g = 255, .b = 255 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id3 = 16,		.r = 0, .g = 0, .b = 255 },
	{ .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id3 = 32,		.r = 255, .g = 0, .b = 255 },


    // { .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id0 = 10, .id1 = 9, .r = 255, .g = 0, .b = 0 },
    // { .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_PATTERN, .id0 = 4, .id1 = 0, .pattern_id = 8 },
    // { .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id0 = 8, .id1 = 0, .r = 0, .g = 255, .b = 0 },
    // { .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_PATTERN, .id = 16, .id1 = 0, .pattern_id = 9 },
    // { .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_RGB, .id0 = 32, .id1 = 0, .r = 0, .g = 0, .b = 255 },
    // { .flags = LED_FLAG_MATCH_ID | LED_FLAG_USE_ROTATE_PATTERN, .id0 = 64, .id1 = 0},
    // { .flags = LED_FLAG_MATCH_ID | LED_FLAG_MATCH_LAYER | LED_FLAG_USE_ROTATE_PATTERN, .id0 = 262144, .id1 = 0, .layer = 0 },
    // { .flags = LED_FLAG_MATCH_ID | LED_FLAG_MATCH_LAYER | LED_FLAG_USE_ROTATE_PATTERN, .id = 16777216, .id1 = 0, .layer = 1 },
    { .end = 1 }
};